# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 15:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter Valid Phone Number (10-digits)', regex='^\\d{10,10}$')])),
                ('registd_date', models.DateTimeField(auto_now_add=True)),
                ('events', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Mad-Arts'), (2, 'Football'), (3, 'Cricket'), (4, 'Treasure-Hunt'), (5, 'Mr&Ms.Furore'), (6, 'Group-Dance'), (7, 'JAM'), (8, 'Sketching')], default=None, max_length=15)),
            ],
        ),
    ]
