# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 22:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0003_auto_20170224_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='registd_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 24, 22, 28, 23, 841552, tzinfo=utc)),
        ),
    ]
