# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0004_auto_20170224_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='registd_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
