# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-06 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0006_auto_20170315_0530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='phone_number',
            new_name='phone_no',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='reg_id',
            new_name='ticket_no',
        ),
        migrations.RemoveField(
            model_name='register',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='register',
            name='events',
        ),
        migrations.AddField(
            model_name='register',
            name='college_name',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
