# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-06 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0008_auto_20190106_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='ticket_cat',
            field=models.CharField(default='silver', max_length=15),
        ),
        migrations.AlterField(
            model_name='register',
            name='reg_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='ticket_no',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
