# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-06 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0009_auto_20190106_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='ticket_cat',
            field=models.CharField(max_length=15),
        ),
    ]
